name: ClickUp Service Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-source:
    name: Build Artifact
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: 21
          cache: 'gradle'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle
        run: ./gradlew bootJar

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: build/libs

  docker-publish:
    needs: build-source
    name: Push Docker Image
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
      
    steps:
      - name: Check out the repo (Dockerfile)
        uses: actions/checkout@v4

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: joelin/clickup-service
      
      - uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: build/libs

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/arm64, linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:          
          subject-name: docker.io/${{ secrets.DOCKER_USERNAME }}/clickup-service
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true      
